write_record: ./write_record.c ../record.c
	gcc write_record.c ../record.c -o write_record
read_record: ./read_record.c ../record.c
	gcc read_record.c ../record.c -o read_record
clean:
	-rm write_record
	-rm read_record
	-rm record_2

